from enum import Enum

class Banco(Enum):
    CENTRAL_BANK = 0
    BANCO_DE_LA_REPÚBLICA = 1
    COMMERCIAL_BANKS = 2
    BANAGRARIO = 3
    BANCAMÍA = 4
    AVVILLAS = 5
    CAJA_SOCIAL = 6
    COLMENA = 7
    BANCO_DE_BOGOTÁ = 8
    BANCO_DE_OCCIDENTE = 9
    BANCO_POPULAR = 10
    BANCO_SANTANDER = 11
    BANCOLOMBIA = 12
    BBVA_COLOMBIA = 13
    CITIBANK_COLOMBIA = 14
    COLPATRIA = 15
    DAVIVIENDA = 16
    GBN_SUDAMERIS = 17
    HELM = 18
    HSBC_COLOMBIA = 19
    PROCREDIT = 20
    RBS_COLOMBIA = 21
